spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: enjuk91@gmail.com
    password: koyunpark1234
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true